### ISSUE TITLE
Add it to bower

### ISSUE THREAD

**Issue by FWeinb** [subprotocol/verlet-js#1]
It would be great to submit this to [bower](https://github.com/twitter/bower). 
Then it would be easer to integrate it in your own projects.

**Comment by subprotocol** [comment]
Sounds like a good idea. I have not used Bower before, so I would need to study it first.

**Comment by FWeinb** [comment]
Great, thanks!

**Comment by aeosynth** [comment]
if you're going to start down the road of package manager support, i'd like this in the [npm](https://npmjs.org/) registry as well

**Comment by FWeinb** [comment]
Why would you want this to be a node package? This is meant for the Browser?

**Comment by aeosynth** [comment]
i already have node's package manager installed, and i can use a build tool such as [commonjs-everywhere](https://github.com/michaelficarra/commonjs-everywhere) to include verlet-js in a browser bundle

**Comment by shama** [comment]
+1 for npm too. Node modules are easily consumable on the browser via build tools. The most popular being [browserify](https://github.com/substack/node-browserify) or another nice one is [webpack](https://github.com/webpack/webpack).

**Comment by subprotocol** [comment]
With https://github.com/subprotocol/verlet-js/pull/14 we are going the npm route with browserify, so I will close out this pull request.  If someone would like to also have it in bower and is willing to submit a contribution please feel free to re-open this. Thanks!

**Comment by shama** [comment]
Yay! Thanks!
